id: I0CB86C36
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T17:59:29+00:00'
last_modified: '2022-06-07T18:50:09.584465+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4072
  title: ཚད་མ་རིགས་པའི་གཏེར་གྱི་རང་འགྲེལ་མཆན་བུ་ཅན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A4EA:
      image_group_id: I3CN6474
      title: ''
      total_pages: 660
      order: 1
      base_file: A4EA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
