id: P003282
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4072
  title: ཚད་མ་རིགས་པའི་གཏེར་གྱི་རང་འགྲེལ་མཆན་བུ་ཅན།
  author: ''
  volumes:
    9ad0342a07d64f00820cd501e03571bc:
      image_group_id: I3CN6474
      title: ''
      volume_number: 1
      total_pages: 660
      base_file: v001.txt
